"""Static (no-LLM) control agent.

Used to characterize the harness's noise floor and quantify how much of
any LLM agent's measured fitness gain is the LLM vs the harness.
Every "agent invocation" is a deterministic placeholder:

  Hypothesis phase:
    Writes a stub hypothesis YAML at the path the orchestrator expects.
    Title is "static-control-noop"; advisory `changes` lists no files;
    motivation/hypothesis text says explicitly that this slot is a
    control. The schema validator accepts it because all required
    fields are present.

  Implementation phase:
    Writes a one-line implementation_notes.md and exits. The agent
    does NOT modify any RTL — the worktree's RTL stays at the active
    branch's tip. The eval gates therefore measure the unchanged
    fixture, which yields delta_pct ≈ 0% (modulo nextpnr-seed
    measurement variance). Pinned seeds [1,2,3] in tools/eval/fpga.py
    keep that variance at 0% in practice.

The agent is invoked exactly the same way as codex/opencode/claude
(it accepts the orchestrator's prompt as its single CLI argument and
writes its outputs to the worktree). _runtime.build_agent_cmd routes
provider="static" to this script.

Detecting which phase we're in:
  - Hypothesis prompts include the literal string "## Hypothesis schema"
    (per the orchestrator's hypothesis prompt template).
  - Implementation prompts include "Edit, create, or delete files in
    the worktree" (per implement.py:_build_prompt).
  - Anything else falls through to a one-line exit so the agent doesn't
    hang on unrecognized prompts.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path


def _hyp_id_from_prompt(prompt: str) -> str | None:
    """Find the hypothesis id the orchestrator pre-allocated for this slot.

    The hypothesis prompt embeds it as `id: hyp-YYYYMMDD-NNN-rNsM`.
    Falling back to None tells the caller to skip the YAML write.
    """
    m = re.search(r"\bhyp-\d{8}-\d{3}-r\d+s\d+\b", prompt)
    return m.group(0) if m else None


def _target_from_prompt(prompt: str) -> str:
    """Find TARGET CORE: cores/<name>/ in the impl prompt; default 'bench'."""
    m = re.search(r"cores/([\w\-]+)/", prompt)
    return m.group(1) if m else "bench"


def _write_static_hypothesis(prompt: str) -> None:
    """Hypothesis-phase response: write a stub YAML for the slot."""
    target = _target_from_prompt(prompt)
    hyp_id = _hyp_id_from_prompt(prompt)
    if not hyp_id:
        # Without a pre-allocated id we'd write a YAML the round
        # whitelist doesn't accept. Better to fail fast than to
        # produce a sandbox violation.
        print("[static-agent] no hypothesis id found in prompt; skipping",
              file=sys.stderr, flush=True)
        return
    yaml_dir = Path("cores") / target / "experiments" / "hypotheses"
    yaml_dir.mkdir(parents=True, exist_ok=True)
    out_path = yaml_dir / f"{hyp_id}.yaml"
    # Schema requires changes to have at least one entry, with `file`
    # under cores/<target>/rtl/ or test/test_*.py. Cite alu.sv as an
    # arbitrary placeholder — the implementation phase will not
    # actually edit it.
    body = (
        f"id: {hyp_id}\n"
        f"title: \"static-control-noop\"\n"
        "category: micro_opt\n"
        "motivation: |\n"
        "  No-LLM control: this slot is generated by tools/agents/static_agent.py\n"
        "  to characterize the harness's noise floor. No RTL changes.\n"
        "hypothesis: |\n"
        "  Make no architectural change. The eval pipeline still runs lint,\n"
        "  formal, cosim, and FPGA fitness against the unchanged fixture.\n"
        "expected_impact:\n"
        "  fitness_delta_pct: 0\n"
        "  confidence: high\n"
        "changes:\n"
        "  - file: rtl/alu.sv\n"
        "    description: |\n"
        "      No-op placeholder to satisfy the hypothesis schema's\n"
        "      changes.minItems=1 requirement. The implementation\n"
        "      phase makes no actual edit.\n"
    )
    out_path.write_text(body)
    print(f"[static-agent] wrote {out_path}", flush=True)


def _write_static_impl_notes(prompt: str) -> None:
    """Implementation-phase response: write notes; touch nothing else."""
    target = _target_from_prompt(prompt)
    notes = Path("cores") / target / "implementation_notes.md"
    notes.parent.mkdir(parents=True, exist_ok=True)
    notes.write_text(
        "Static (no-LLM) control: no RTL changes made.\n"
        "Eval gates run against the unchanged fixture; expected delta ~0%.\n"
    )
    print(f"[static-agent] wrote {notes}", flush=True)


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    if not argv:
        print("[static-agent] no prompt provided; nothing to do",
              file=sys.stderr, flush=True)
        return 0
    prompt = argv[0]
    # Phase detection — see module docstring.
    if "## Hypothesis schema" in prompt or "hypothesis YAML" in prompt:
        _write_static_hypothesis(prompt)
    elif "Edit, create, or delete files in the worktree" in prompt \
            or "implementation_notes.md" in prompt:
        _write_static_impl_notes(prompt)
    else:
        # Unknown phase — print the first 80 chars of the prompt so a
        # future maintainer can extend the recognizer.
        print(f"[static-agent] unrecognized prompt; first 80 chars: "
              f"{prompt[:80]!r}", file=sys.stderr, flush=True)
    # Optional --output-last-message <path> compatibility (codex
    # convention; the orchestrator passes it for codex but not for
    # other runtimes — accept it gracefully if present).
    if "--output-last-message" in argv:
        i = argv.index("--output-last-message")
        if i + 1 < len(argv):
            try:
                Path(argv[i + 1]).write_text("static-agent: done\n")
            except OSError:
                pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
